name: build

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive Linux X64 binary
        uses: actions/upload-artifact@v4
        with:
          path: app/build/bin/linuxX64/releaseExecutable/activitypub-to-finger.kexe
          # carm is the best
          name: activitypub-to-finger-linuxX64

      - name: Archive Linux Arm64 binary
        uses: actions/upload-artifact@v4
        with:
          path: app/build/bin/linuxArm64/releaseExecutable/activitypub-to-finger.kexe
          name: activitypub-to-finger-linuxArm64

      - name: Archive JVM binary
        uses: actions/upload-artifact@v4
        with:
          path: main-jvm/build/distributions/activitypub-to-finger-1.0.0.zip
          name: activitypub-to-finger-jvm
